export enum PokemonTypeEnum {
    'bug' = 'Inseto',
    'dark' = 'Noturno',
    'dragon' = 'Dragão',
    'electric' = 'Elétrico',
    'fairy' = 'Fada',
    'fighting' = 'Lutador',
    'fire' = 'Fogo',
    'flying' = 'Voador',
    'ghost' = 'Fantasma',
    'grass' = 'Planta',
    'ground' = 'Terra',
    'ice' = 'Gelo',
    'normal' = 'Normal',
    'poison' = 'Venenoso',
    'psychic' = 'Psíquico',
    'rock' = 'Pedra',
    'steel' = 'Metálico',
    'water' = 'Água'
}